Recipes/Models/ErrorViewModel.cs
using System;

namespace Recipes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Recipes/Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Recipes.Models
{
    public class Recipe
    {
        [Key]
        public int Id { get; set; }
        public string RecipeName { get; set; }
    }
}

Recipes/Models/Token.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Recipes.Models
{
    public class Token
    {
        [JsonPropertyName("accessToken")]
        public string AccessToken { get; set; }
        [JsonPropertyName("refreshToken")]
        public string RefreshToken { get; set; }
        public DateTime? RefreshTokenExpiration { get; set; }
    }
}

Recipes/Models/User.cs
using EasyAuth;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Recipes.Models
{
    public class User
    {
        [Key]
        public long Id { get; set; }
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        public string Email { get; set; }
        public bool IsVerified { get; set; }
        public string RefreshToken { get; set; }
        public DateTime RefreshTokenExpiration { get; set; }
    }
}

Recipes/Controllers/AuthorizationApiController.cs
using EasyAuth;
using EasyAuth.Utils.PasswordUtil;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Recipes.Dtos.User;
using Recipes.Models;
using Recipes.Repositories;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Recipes.Controllers
{
    [Route("api/oauth")]
    [ApiController]
    public class AuthorizationApiController : ControllerBase

    {
        private readonly UserRepository _userRepository;
        public AuthorizationApiController(
            UserRepository userRepository
            )
        {
            _userRepository = userRepository;
        }
        [HttpPost("register")]
        [AllowAnonymous]
        public async Task<ActionResult> CreateUser(UserCreateDto userCreateDto)
        {

            if (!ModelState.IsValid)
            {
                return BadRequest("validation errors found");
            }

            var protectedPassword = PasswordHasher.Hashify(userCreateDto.Password, userCreateDto.Username);

            var apiUserModel = userCreateDto.Adapt<User>();
            apiUserModel.Password = protectedPassword;

            await _userRepository.CreateUser(apiUserModel);

            var tokenResponse = await _userRepository.AuthorizeWithPasswordGetToken(apiUserModel, userCreateDto.Password);
            var response = new
            {
                info = "user has been created successfully",
            };

            if (tokenResponse != null)
            {
                CreateSessionCookie(tokenResponse);
            }
            return Ok(response);
        }

        private void CreateSessionCookie(TokenModel tokenModel)
        {
            var cookieOptions = new CookieOptions()
            {
                Path = "/",
                IsEssential = true,
                HttpOnly = false,
                Secure = false
            };
            HttpContext.Response.Cookies.Append("session", tokenModel.AccessToken, cookieOptions);
            HttpContext.Response.Cookies.Append("refresh_session", tokenModel.RefreshToken, cookieOptions);
        }

        [HttpPost("login")]
        public async Task<ActionResult> Login(UserCreateDto userCreateDto)
        {
            var inputPassword = userCreateDto.Password;

            var foundUser = await _userRepository.GetUserByName(userCreateDto.Username);

            if (foundUser == null)
            {
                return Ok("User not found");
            }
            var tokenResponse = await _userRepository.AuthorizeWithPasswordGetToken(foundUser, inputPassword);

            if (tokenResponse == null)
            {
                return Ok("Password not validated :(");
            }

            CreateSessionCookie(tokenResponse);
            return Ok($"Success logging in, access token: {tokenResponse.AccessToken}");
        }


        //[HttpPost("refresh")]
        //public async Task<ActionResult> Refresh([FromBody] TokenModel tokenModel)
        //{
        //    if (tokenModel == null)
        //    {
        //        return BadRequest("must provide access and refresh token");
        //    }

        //    string accessToken = tokenModel.AccessToken;
        //    string refreshToken = tokenModel.RefreshToken;

        //    var principal = _tokenizationService.GetPrincipalFromExpiredToken(accessToken);

        //    if (principal == null)
        //    {
        //        return BadRequest("Refresh token not validated");
        //    }

        //    var username = principal.Identity.Name;

        //    var user = await _userRepository.GetUserByName(username);
        //    if (user == null || user.RefreshToken != refreshToken || user.RefreshTokenExpiration <= DateTime.UtcNow)
        //    {
        //        return BadRequest("Invalid client credentials: bad refresh token or user not found");
        //    }

        //    var identity = _userRepository.GetIdentity(user);
        //    var newAccessToken = _tokenizationService.GenerateAccessToken(identity, JWTTokenTypes.Authorization);
        //    var newRefreshToken = _tokenizationService.GenerateRefreshToken();

        //    await _userRepository.SetRefreshTokenForUser(
        //        name: user.Username,
        //        refreshToken: newRefreshToken,
        //        refreshTokenExpiration: DateTime.UtcNow.AddDays(1));

        //    return new ObjectResult(new
        //    {
        //        accessToken = newAccessToken,
        //        refreshToken = newRefreshToken
        //    });
        //}

        //[Authorize]
        //[HttpPost("revoke")]
        //public async Task<IActionResult> Revoke()
        //{
        //    var username = User.Identity.Name;

        //    await _userRepository.RevokeRefreshTokenForUser(username); //revoke token
        //    return NoContent();
        //}

        [Authorize]
        [HttpGet("secret")]
        public ActionResult Secret()
        {
            return Ok($"Your login: {User.Identity.Name}");
        }
    }
}

Recipes/Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Recipes.Controllers
{
    public class AuthorizationController : Controller
    {
        public IActionResult Index() //login as another user, sign out, register, log in
        {
            return View();
        }

        [HttpGet]
        public IActionResult Secretushka()
        {
            var username = User.Identity.Name ?? "bitch";
            return View(model: username);
        }

        public IActionResult Register()
        {
            return View();
        }
    }
}

Recipes/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Recipes.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Recipes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Recipes/Views/Authorization/Index.cshtml
@model Recipes.Models.User

<form asp-controller="Authorization" asp-action="Login" method="get">
    <div>
        <input type="text" name="userName"/>
        <label>Username</label>
    </div>
    <div>
        <input type="password" name="password" />
        <label>Password</label>
    </div>
    <input type="submit"/>
</form>

Recipes/Views/Authorization/Secretushka.cshtml
@model string

@{
    ViewData["Title"] = "Secretushka";
}

<h1>Secretushka @Model</h1>

Recipes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Recipes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Recipes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Recipes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Recipes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>